### ISSUE TITLE
PIR Motion Sensor - Manufacturer ID _TZE200_3towulqd TS0601 no motion detected

### ISSUE THREAD

**Issue by TzK069** [JohanBendz/com.tuya.zigbee#780] opened 2024-03-06 15:36 UTC
It senses motion (turns red) but it not reports in the homey pro 2023 

![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/159542871/32cca39e-7035-45e4-8cd9-046ffea8c158)

**Comment by Boechie** [comment] 2024-04-08 20:33
There is development going on for this device. See PR #724 and #740. Maybe those PRs will solve this.

**Comment by MartinSjoberg** [comment] 2024-04-30 08:22
Hi Guys. I am having the same issue described above with the sensor. I am on app version v0.2.25test. Is the above mentioned PRs not released yet or is there a problem with them? Thank you for your work.

**Comment by Wuma68** [comment] 2024-05-07 12:50
Hi again to all, it seams that all work on this have stoped at februari or is it still going on without our knowledge! :)

**Comment by MartinSjoberg** [comment] 2024-05-07 13:04
Yeah well 503 open issues and 5 issues closed the last month. Too bad it looks like a nice little sensor :-) I guess the maintainers are to few and overworked.

**Comment by Boechie** [comment] 2024-05-07 13:52
@Wuma68 @MartinSjoberg Yes development is still going on. Multiple people including @mihaiINW (my colleague) and @maccyber are working on it. See PR #724  and #740 . The problem is that there are apparently 2 different hardware versions of the device, but they both report as the same device. The solutions from both PRs work (for 1 of the hardware versions each), but we are still figuring out how to merge them. So for now only 1 hardware version is supported. Apparently you have the other unsupported hardware version. In our company we use many (>40) of these devices and it turns out we have a mix of both hardware versions. So having a proper solution that supports both version is of great importance to ourselves. The problem is that development capacity to do work for free is very scarce...

**Comment by MartinSjoberg** [comment] 2024-05-07 13:56
No worries. Just tell me if I can help with anything. I have no exprience with adding sensors to homey though. :-)

**Comment by Wuma68** [comment] 2024-05-07 14:52
Exactly no worries, we are just glad that someone working on it.

@Boechie Is the config only stored in driver or is it moved to device after you have set up a new device?

**Comment by ericvanbeurden** [comment] 2024-10-08 19:16
Confirmed, experiencing the same bug.
Device is recognized however doesn't give any alarms.
I will wait until the next update.

**Comment by claypole** [comment] 2024-11-25 17:11
I am having the same issue. Any updates on when this might be fixed?

When I try to update any parameters for the device, I get the error "Could not get device by ID".

Here is the interview from the device, if that helps:

  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_3towulqd"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:f0:44:a6:a9:05",
    "networkAddress": 58822,
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_3towulqd",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 58822,
        "_reserved": 18,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          1280,
          1,
          1024
        ],
        "outputClusters": []
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "swBuildId": "0122052017",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "motionSensor"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    1,
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "5c:c7:c1:ff:fe:5b:e9:d3"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "illuminanceMeasurement": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "measuredValue",
                "value": 32619,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "minMeasuredValue",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 4000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      }
    }
  }

**Comment by JohanBendz** [comment] 2024-12-18 21:25
Fixed in next release.

**Closed as completed by JohanBendz** 2024-12-18 21:25 UTC
Labels: bug
