### ISSUE TITLE
Bug report - Adds as basic zigbee instead of power strip

### ISSUE THREAD

**Issue by Netwitz** [JohanBendz/com.tuya.zigbee#702] opened 2024-01-28 17:07 UTC
I am in the U.S. and have a few WiFi/Zigbee Tuya power strips. Even though the plugs are different in this country from what you have in the Tuya app, I was able to add a 4 plug power strip with no problems to my Homey Pro. When I tried to add a second one using the same process, I get an error with unknown Zigbee device. It still adds the device, but only has option for on/off. It doesn’t give options for each individual plug. I restarted the Tuya Zigbee app, but that didn’t help. 

**To Reproduce*I have your Tuya Zigbee app installed on my Homey Pro. 
1. Go to Devices and tap + New device. 
2. Click on Tuya Zigbee app
3. Scroll down to Wall Plug
4. Select Power strip socket 1/4
5. Tap Connect then on Zigbee page tap Continue
6. Put power strip into pairing mode

**Expected behavior**
I was expecting it to add a device with 4 sockets and a single USB control. Instead it added a basic single Zigbee device without the individual socket options. As you can see in the screenshot below, the 1st power strip was added successfully. Then get error on second try as described. 

**App and Homey version**
What Homey version are you running? Homey Pro (Early 2023) 
What version of Homey firmware do you use? 10.2.1
What version of the Tuya Zigbee App are you using? 0.1.45
Homey app version 7.6.1.1408 

**Screenshots**
![IMG_1953](https://github.com/JohanBendz/com.tuya.zigbee/assets/73721714/8133bfd4-73e5-4eaf-a93f-e036772baa4c)
![IMG_1954](https://github.com/JohanBendz/com.tuya.zigbee/assets/73721714/cb69bae1-c915-40d1-8bad-3a2671c11808)
![IMG_1955](https://github.com/JohanBendz/com.tuya.zigbee/assets/73721714/debc7fbb-ba98-4b3b-8c83-dbb543736239)
![IMG_1956](https://github.com/JohanBendz/com.tuya.zigbee/assets/73721714/49ebd956-048d-4c58-a0be-150ed8eeeea9)

**Additional context**
I realize since the sockets are different being in different countries, but since the first one worked perfectly, I figured the others added would act the same way.

**Comment by obetsak** [comment] 2024-01-28 21:15
For a device to work with tuya zigbee app the model and manufacturer id must match a device in the list of devices that this app support. Even if you have two devices that even looks identical one could work and the other one not just because they have different ids. This is by design. If you look here https://tools.developer.homey.app/tools/zigbee you can see you device id for each device.

**Comment by Boechie** [comment] 2024-02-08 23:28
@Netwitz , Did you try the TEST version of the app? Install from here: https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/ From your reported version (v 0.1.45) I think you did not. After installing it, your device might just work. If not (and still being (un)recognized as an unknow zigbee device), you should **open a New Device issue** and mark it as such. See guidelines. **And then close this issue.** Your 'problem' is **not a bug**, but merely a new device request.

**Comment by Netwitz** [comment] 2024-02-09 01:54
Thank you for your response. I'll check the newer app.


     On Thursday, February 8, 2024 at 06:29:10 PM EST, Boechie ***@***.***> wrote:  
 
 


@Netwitz , Did you try the TEST version of the app? Install from here: https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/ From your reported version (v 0.1.45) I think you did not. After installing it, your device might just work. If not (and still being (un)recognized as an unknow zigbee device), you should open a New Device issue and mark it as such. See guidelines. And then close this issue. Your 'problem' is not a bug, but merely a new device request.

**Closed as completed** 2024-09-02 21:07 UTC
Labels: bug
